[versions]
agp = "8.7.3"
kotlin = "2.2.0"
android-minSdk = "24"
android-compileSdk = "35"
compose-multiplatform = "1.8.0"
compose-activity = "1.10.1"
androidx-lifecycle = "2.9.1"
rive-android = "10.3.2"
androidx-startup = "1.2.0"
spmForKmp = "1.0.0-Beta02"
pullrefresh = "1.4.0-beta03"
dokka = "2.0.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
rive-android = { group = "app.rive", name = "rive-android", version.ref = "rive-android" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }
materii-pullrefresh = { group = "dev.materii.pullrefresh", name = "pullrefresh", version.ref = "pullrefresh" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.31.0" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spmForKmp = { id = "io.github.frankois944.spmForKmp", version.ref = "spmForKmp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }